language: python
python:
    - "3.6"

# Install dependencies
install:
    - pip install -r requirements.txt

# Run tests
script:
    - pytest

# Specify build branch
branches:
      only:
        - api-travis-ci-159102302